### ISSUE TITLE
Conda environment

### ISSUE THREAD

**Issue by aanugraha** [ImperialCollegeLondon/spear-tools#1]
I created a new Conda environment using the provided `env-spear-metrics.yml` and followed `run_example.sh`.

I got the following error messages when I ran `spear_evaluate.py`:
`python spear_evaluate.py spear_data/Main/Dev  my_results/audio_passthrough_20221115  segments_Dev.csv my_results/metrics/passthrough_Dev_D2_S10_M00.csv  --list_cases D2 10 00`
```
Traceback (most recent call last):
  File "spear_evaluate.py", line 23, in <module>
    import pysepm
  File "/mnt/ssd22/projects/spear/conda_envs/spear_challenge/lib/python3.8/site-packages/pysepm/__init__.py", line 4, in <module>
    from .qualityMeasures import fwSNRseg,SNRseg,llr,wss,composite,pesq,cepstrum_distance
  File "/mnt/ssd22/projects/spear/conda_envs/spear_challenge/lib/python3.8/site-packages/pysepm/qualityMeasures.py", line 4, in <module>
    import pesq as pypesq # https://github.com/ludlows/python-pesq
  File "/mnt/ssd22/projects/spear/conda_envs/spear_challenge/lib/python3.8/site-packages/pesq/__init__.py", line 5, in <module>
    from ._pesq import pesq, pesq_batch
  File "/mnt/ssd22/projects/spear/conda_envs/spear_challenge/lib/python3.8/site-packages/pesq/_pesq.py", line 8, in <module>
    from .cypesq import cypesq, cypesq_retvals, cypesq_error_message as pesq_error_message
  File "pesq/cypesq.pyx", line 1, in init cypesq
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

Similar issues have been reported in other repositories:
* https://github.com/NVIDIA/NeMo/issues/3501
* https://github.com/facebookresearch/denoiser/issues/112

It seems that there are compatibility issues between different versions of `numpy`, `pesq`, `pysepm`, and also `numba`, [which is required by `pysepm`](https://github.com/schmiph2/pysepm/blob/3c3f35ef5846d0e976adbc9d72469c3d4ae99a4f/setup.py#L14).

Interestingly, I don't have `numba` in this environment:
```
$ conda list | grep "python.*3.8\|numpy\|numba\|pesq\|pysepm"
numpy                     1.21.6                   pypi_0    pypi
pesq                      0.0.4                    pypi_0    pypi
pypesq                    1.2.4                    pypi_0    pypi
pysepm                    0.1                      pypi_0    pypi
python                    3.8.15               h3fd9d12_0  
```
`numba` exists in my base Conda environment, though.

Could you share the versions of your installed packages?
I would appreciate any suggestions on solving this compatibility issue.

**Comment by aanugraha** [comment]
I solved the issue by creating another new environment using a **modified** `env-spear-metrics.yml`, where I changed `python=3.8` to `python=3.9`.
```
$ conda list | grep "python.*3.9\|numpy\|numba\|pesq\|pysepm"
numba                     0.56.4                   pypi_0    pypi
numpy                     1.23.4           py39h14f4228_0  
numpy-base                1.23.4           py39h31eccc5_0  
pesq                      0.0.4                    pypi_0    pypi
pypesq                    1.2.4                    pypi_0    pypi
pysepm                    0.1                      pypi_0    pypi
python                    3.9.15               haa1d7c7_0  
```
Using this new environment with Python 3.9, I could run the provided `run_example.sh` successfully.

The different versions of packages might affect the computations of performance metrics, though.
I will cross-check the performance scores with [the reference ones](https://github.com/ImperialCollegeLondon/spear-tools/tree/9f21d83ac13310b7e9384b62aa32ed7489242728/results).

**Comment by aanugraha** [comment]
I would say that my environment with Python 3.9 is fine. The figures below show the differences between the scores I got (denoted by `run1`) and [the reference scores](https://github.com/ImperialCollegeLondon/spear-tools/tree/9f21d83ac13310b7e9384b62aa32ed7489242728/results) (denoted by `ref`). Based on most of the figures, generally speaking, the baseline method and the score computation work as expected using this environment.

There are two separate issues, though.
* The first one is about the randomness aspect of the HASPI score computation. I have opened another GitHub issue about this (https://github.com/ImperialCollegeLondon/spear-tools/issues/2) and proposed a workaround for reproducibility purposes.
* The second one is about the performance discrepancies for the baseline method on the Dev D4 dataset. I wonder what the problem is. Could someone from the challenge organizers (probably, @PGuiraud) comment on this?

| |  Dev D1 | Dev D2 | Dev D3 | Dev D4 |
|---|---|---|---|---|
Passthrough | ![notseeded_diff_ref_run1_passthrough_Dev_D1](https://user-images.githubusercontent.com/18207089/203212995-be853407-3331-4507-acc2-dd48ff151e9d.png) | ![notseeded_diff_ref_run1_passthrough_Dev_D2](https://user-images.githubusercontent.com/18207089/203212997-033f10d1-e279-48d2-8433-dc1d7e388c6d.png) | ![notseeded_diff_ref_run1_passthrough_Dev_D3](https://user-images.githubusercontent.com/18207089/203213000-5f268546-7524-47cc-9771-3be886d25bbe.png) | ![notseeded_diff_ref_run1_passthrough_Dev_D4](https://user-images.githubusercontent.com/18207089/203213004-2f200534-58c5-4632-a06c-40e88a250eab.png)
Baseline | ![notseeded_diff_ref_run1_baseline_Dev_D1](https://user-images.githubusercontent.com/18207089/203212982-fc8b44cb-6ac0-40cd-8175-3bd32d65faec.png) | ![notseeded_diff_ref_run1_baseline_Dev_D2](https://user-images.githubusercontent.com/18207089/203212987-df4f1fb7-aeaf-44c5-b34d-7acf65cbd4fb.png) | ![notseeded_diff_ref_run1_baseline_Dev_D3](https://user-images.githubusercontent.com/18207089/203212990-34b62e4b-d5d5-4cad-897e-8b9e568b978e.png) | ![notseeded_diff_ref_run1_baseline_Dev_D4](https://user-images.githubusercontent.com/18207089/203212993-24e319a2-c83a-4eb5-b648-6f17c8178444.png)

**Comment by PGuiraud** [comment]
Thank you @aanugraha for noticing this conflict in the packages.
There originally was a similar conflict between `pysepm` and `speechmetrics` packages but this was resolved before the release of the challenge. We have not heard of anyone else running into a similar problem but we are thankful that you found and shared a solution.

I replied to #2 directly but regarding the discrepancies in baseline D4 this is very interesting. One would expect this error to be also in D1, D2 and D3 if the baseline algorithm was to blame or in passthrough D4 if D4 was the issue but it doesn't seem like it.
We will investigate further but for now given that the errors are in the magnitude of 1e-5 this is not too significant and you can continue with the challenge without much worry.

**Comment by aanugraha** [comment]
Thank you for the response!

> One would expect this error to be also in D1, D2 and D3 if the baseline algorithm was to blame or in passthrough D4 if D4 was the issue but it doesn't seem like it.

This is exactly what baffles me.
It would be useful if someone else could share whether they can reproduce the reference scores using the publicly available datasets and scripts.
I agree that the score differences are not too significant, though.
